DISTRICTS = [
    {
        "id": "almora",
        "name": "Almora",
        "latitude": 29.5892,
        "longitude": 79.6467,
        "risk": "High",
        "score": 76,
        "threat": "Landslide",
        "color": "#f97316",
        "type": "District",
    },
    {
        "id": "chamoli",
        "name": "Chamoli",
        "latitude": 30.4028,
        "longitude": 79.3188,
        "risk": "Critical",
        "score": 91,
        "threat": "Landslide",
        "color": "#ef4444",
        "type": "District",
    },
    {
        "id": "rudraprayag",
        "name": "Rudraprayag",
        "latitude": 30.2844,
        "longitude": 78.9811,
        "risk": "High",
        "score": 82,
        "threat": "Flash Flood",
        "color": "#f97316",
        "type": "District",
    },
    {
        "id": "uttarkashi",
        "name": "Uttarkashi",
        "latitude": 30.7268,
        "longitude": 78.4354,
        "risk": "Critical",
        "score": 78,
        "threat": "Landslide",
        "color": "#ef4444",
        "type": "District",
    },
    {
        "id": "pithoragarh",
        "name": "Pithoragarh",
        "latitude": 29.5829,
        "longitude": 80.2182,
        "risk": "High",
        "score": 74,
        "threat": "Earthquake",
        "color": "#f97316",
        "type": "District",
    },
    {
        "id": "bageshwar",
        "name": "Bageshwar",
        "latitude": 29.8376,
        "longitude": 79.7724,
        "risk": "Medium",
        "score": 61,
        "threat": "Landslide",
        "color": "#eab308",
        "type": "District",
    },
    {
        "id": "nainital",
        "name": "Nainital",
        "latitude": 29.3919,
        "longitude": 79.4542,
        "risk": "Medium",
        "score": 57,
        "threat": "Landslide",
        "color": "#eab308",
        "type": "District",
    },
    {
        "id": "dehradun",
        "name": "Dehradun",
        "latitude": 30.3165,
        "longitude": 78.0322,
        "risk": "Medium",
        "score": 52,
        "threat": "Flood",
        "color": "#eab308",
        "type": "District",
    },
    {
        "id": "haridwar",
        "name": "Haridwar",
        "latitude": 29.9457,
        "longitude": 78.1642,
        "risk": "Low",
        "score": 34,
        "threat": "Flood",
        "color": "#22c55e",
        "type": "District",
    },
]


ALMORA_LOCATIONS = [
    {
        "id": "almora-city",
        "name": "Almora City",
        "latitude": 29.5892,
        "longitude": 79.6467,
        "risk": "Medium",
        "score": 54,
        "threat": "Landslide",
        "color": "#eab308",
        "type": "City",
    },
    {
        "id": "kasar-devi",
        "name": "Kasar Devi",
        "latitude": 29.6565,
        "longitude": 79.6534,
        "risk": "High",
        "score": 71,
        "threat": "Landslide",
        "color": "#f97316",
        "type": "Locality",
    },
    {
        "id": "binsar",
        "name": "Binsar",
        "latitude": 29.7047,
        "longitude": 79.7513,
        "risk": "Medium",
        "score": 62,
        "threat": "Forest Fire",
        "color": "#eab308",
        "type": "Forest Area",
    },
    {
        "id": "jageshwar",
        "name": "Jageshwar",
        "latitude": 29.6409,
        "longitude": 79.8545,
        "risk": "Medium",
        "score": 58,
        "threat": "Landslide",
        "color": "#eab308",
        "type": "Heritage Area",
    },
    {
        "id": "dwarahat",
        "name": "Dwarahat",
        "latitude": 29.7797,
        "longitude": 79.4274,
        "risk": "Low",
        "score": 38,
        "threat": "Earthquake",
        "color": "#22c55e",
        "type": "Town",
    },
    {
        "id": "ranikhet",
        "name": "Ranikhet",
        "latitude": 29.6434,
        "longitude": 79.4322,
        "risk": "Medium",
        "score": 49,
        "threat": "Landslide",
        "color": "#eab308",
        "type": "Town",
    },
]


RISK_ZONES = [
    {
        "id": "almora-zone",
        "name": "Almora High Risk Zone",
        "latitude": 29.5892,
        "longitude": 79.6467,
        "radius": 14500,
        "risk": "High",
        "color": "#f97316",
        "opacity": 0.38,
    },
    {
        "id": "chamoli-zone",
        "name": "Chamoli Critical Zone",
        "latitude": 30.4028,
        "longitude": 79.3188,
        "radius": 19000,
        "risk": "Critical",
        "color": "#ef4444",
        "opacity": 0.48,
    },
    {
        "id": "rudraprayag-zone",
        "name": "Rudraprayag High Risk Zone",
        "latitude": 30.2844,
        "longitude": 78.9811,
        "radius": 13000,
        "risk": "High",
        "color": "#f97316",
        "opacity": 0.38,
    },
    {
        "id": "pithoragarh-zone",
        "name": "Pithoragarh Moderate Zone",
        "latitude": 29.5829,
        "longitude": 80.2182,
        "radius": 11000,
        "risk": "Medium",
        "color": "#eab308",
        "opacity": 0.32,
    },
]